urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'monitor'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register-crash/(?P<host>host[0-9]{3}\.jc\.rl\.ac\.uk)$',
        views.registerCrash, name="registerCrash"),
    url(r'^saved-crash/(?P<i>[0-9]+$)', views.detailOfCrash,
        name="savedCrash")
] + (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
     static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

templates/monitor/base.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static "monitor/css/bootstrap.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "monitor/css/base.css" %}">
    </head>
    <body>


        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">Lotus Mon</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li class="dropdown {% if not latestCrashes %}disabled{% endif %}">
                  <a class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Latest Crashes <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% for host, date, id in latestCrashes %}
                            <li><a class="dropdown-item" href="{% url 'monitor:savedCrash' id %}">{{ host }} @ {{ date }}</a></li>
                        {% empty %}
                            No crashes are available.
                        {% endfor %}
                  </ul>
                </li>
                <li>
                  <a href="/admin">Admin Panel</a>
                </li>
              </ul>
              <span class="navbar-text navbar-right">
                {% block baseInfo %}
                {% endblock %}
              </span>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>

        <div>
            {% block baseContent %}
            {% endblock %}
        </div>
    </body>
    <script src="{% static "monitor/js/jquery-3.1.1.min.js" %}"></script>
    <script src="{% static "monitor/js/tether.min.js" %}"></script>
    <script src="{% static "monitor/js/bootstrap.min.js" %}"></script>
</html>

templates/monitor/detailOfCrash.html
{% extends "monitor/base.html" %}
{% debug %}
{% block baseContent %}
    {% if crash and ganglias %}
        <div class="page-header">
            <center>
                <h1>{{ crash.host }} <small>{{ crash.date }}</small></h1>
            </center>
        </div>
        <ul class="nav nav-tabs nav-justified" id="tabSwitcher">
          <li class="active"><a data-toggle="tab" href="#lsf">LSF Info</a></li>
          <li><a data-toggle="tab" href="#ganglia">Ganglia</a></li>
        </ul>
        <div class="tab-content">
            <div id="lsf" class="tab-pane active">
                {% if noLsfData %}
                    <center>
                        No LSF data for this crash (probably nothing running).
                    </center>
                {% else %}
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table class="table table-condensed">
                                    <thead>
                                        {% for lsfHead in lsfHeaders %}
                                            <th> {{lsfHead}} </th>
                                        {% endfor %}
                                    </thead>
                                    <tbody>
                                        {% for lsfRow in lsfRows %}
                                            <tr>
                                                {% for lsfCol in lsfRow %}
                                                    <td style="white-space: nowrap;">
                                                        {{ lsfCol}}
                                                    </td>
                                                {% endfor %}
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <center>
                        <a href="{{ crash.lsfData.url }}"> LSF as csv</a>
                    </center>
                {% endif %}
            </div>
            <div id="ganglia" class="tab-pane">
                <div class="row">
                    {% for ganglia in ganglias %}
                            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                                <img class="graph" style="width:100%" src="{{ ganglia.image.url }}"></img>
                            </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        <p>This crash isn't avaliable / doesn't exist!</p>
    {% endif %}
{% endblock %}

{% block baseInfo %}
    {{ crash.host }}
{% endblock %}

templates/monitor/index.html
{% extends "monitor/base.html" %}
{% block baseContent %}
    <div class="row">
        <div class="col-md-12 center-block text-center">
            Register Crash <input type="text" id="hostNameIN"></input>
            <a id="linkToHostOUT"></a>
            <script>
                hostNameIN.addEventListener("input", function(e){
                    host = e.target.value;
                    linkToHostOUT.innerText = "Register Crash On: host"+ host +".jc.rl.ac.uk";
                    linkToHostOUT.href = "/register-crash/host"+host+".jc.rl.ac.uk";
                })
            </script>
        </div>
    </div>
    <center>
        <h3>
            Crashes <span class="badge">{{crashesByDate|length}}</span>
        </h3>
    </center>
    <div class="row">
        <div class="col-sm-4">
            <h4>By Date</h4>
            <div class="list-group">
            {% for crash in crashesByDate %}
                <a href="{% url 'monitor:savedCrash' crash.id %}" class="list-group-item"> {{ crash.date }} - {{ crash.host }}</a></li>
            {% empty %}
            No crashes saved.
            {% endfor %}
            </div>
        </div>
        {% for listTitle, listData, colSize in listByThis %}
        <div class="col-sm-{{colSize}}">
            <h4>By {{ listTitle }} <span class="badge">{{ listData|length}}</span></h4>
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            {% for crashesForThis, name, thisInfo in listData %}
                {% with stringcount=forloop.counter|stringformat:"s" %}
                {% with headingID="heading"|add:listTitle|add:stringcount collapseID="collapse"|add:listTitle|add:stringcount %}
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id='{{ headingID }}'>
                        <h4 class="panel-title">
                            <a {% if forloop.counter0 != 0 %}class="collapsed"{% endif %} role="button" data-toggle="collapse" data-parent="#accordion" href="#{{ collapseID }}" aria-expanded="true" aria-controls="{{ collapseID }}">
                                {{ name}}
                            </a>
                            <span class="badge" style="float:right;">{{crashesForThis|length}}</span>
                        </h4>
                    </div>
                    <div id="{{ collapseID }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="{{ headingID }}">
                        <div class="panel-body">
                            <div class="list-group">
                        {% if thisInfo %}
                            <div class="list-group-item">
                                <pre>{{thisInfo}}</pre>
                            </div>
                        {% endif %}
                        {% for crash in crashesForThis %}
                                <a href="{% url 'monitor:savedCrash' crash.id %}" class="list-group-item">
                                    {% if listTitle != "Hostname" %}
                                        {{ crash.host.address }} @
                                    {% endif %}
                                    {{ crash.date }}
                                </a></li>
                        {% empty %}
                        no crashes saved
                        {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                {% endwith %}
                {% endwith %}
            {% empty %}
            No crashes saved.
            {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>



{% endblock %}

templates/monitor/registerCrashTemplate.html
{% extends "monitor/base.html" %}
{% block baseContent %}
    <div>
        {% if worked %}
            Crash Registered at {{ host }}
        {% else %}
            Crash Register Failed for {{ host }}!
            {{ info }}
        {% endif %}
    </div>
{% endblock %}